name: parse_route
description: A package that parses your routes, and their parameters.
version: 1.0.0
homepage: https://github.com/jonataslaw/parse_route

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.23.1
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
